# Generated by Django 5.1.1 on 2024-09-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHorario', models.DateTimeField()),
                ('nomeCliente', models.CharField(max_length=256)),
                ('emailField', models.EmailField(max_length=254)),
                ('telefoneCliente', models.CharField(max_length=11)),
            ],
        ),
    ]
