# Generated by Django 5.1.1 on 2024-09-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='emailField',
            new_name='emailCliente',
        ),
    ]
