# Generated by Django 5.1.1 on 2024-09-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_rename_emailfield_agendamento_emailcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='nomeCliente',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
