# Generated by Django 5.1.1 on 2024-09-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_agendamento_nomecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='canceladoCliente',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
